#!/usr/bin/env ruby
require 'jwt'
require 'clipboard'
require_relative File.join('..', 'lib', 'dialog')

SECRET = 'SECRET NAME'

puts 'Starting with JWT token generation.'
dialog = Dialog.new
dialog.ask_params

if dialog.valid?
  token = JWT.encode(dialog.params, SECRET, 'HS256')
  Clipboard.copy token
  puts 'The JWT has been copied to your clipboard!'
else
  abort dialog.error_messages.join(', ')
end
